from __future__ import division
import numpy as np
from . import A_vee_B
from .afis_utils import Gaussian

# ============================================================================
# Utility Functions
# ============================================================================

def _is_gaussian(x):
    """Check if x is a Gaussian membership function."""
    return isinstance(x, Gaussian)


def _has_gaussian_input(input_list):
    """Check if any dimension of the input is Gaussian."""
    for inp in input_list:
        if _is_gaussian(inp):
            return True
    return False


def _get_input_core(inp):
    """
    Extract core bounds from an input (for D_LR calculation).
    
    For Gaussian: returns (center, center) - point core
    For [a,b,c,d]: returns (b, c) - interval core
    """
    if _is_gaussian(inp):
        return [inp.center, inp.center]
    else:
        # [a, b, c, d] format
        return [inp[1], inp[2]]


def format_FN_N_Dim(fuzzy_number_n_dim, ftype='crisp_input'):
    ''' Given a fuzzy number, it changes its format to the admissible format supported by A_vee_B script suported types. 
    For now, two ftypes of inputs are supported
    - n dimensional crisp input (list)
    - n dimensional fuzzy antecedent (generated by Renato Lopes Moura wang mendel algorithm)
    - 1d consequent (generated by Renato Lopes Moura wang mendel algorithm)
    - Gaussian inputs are passed through unchanged (handled specially in A_FIS)
    
    Examples
    - 2D crisp input: [a,b] to [[a,a,a,a], [b,b,b,b]] 
    - 1D rule antecedent: see code below. '''

    FN_Ndim_adapted = []
    if ftype == 'crisp_input':  # Intended for crisp inputs (typical case)
        for comp_input in fuzzy_number_n_dim:
            # If Gaussian, pass through unchanged
            if _is_gaussian(comp_input):
                FN_Ndim_adapted.append(comp_input)
            else:
                FN_Ndim_adapted.append([comp_input] * 4)

    elif ftype == 'rule_antecedent':  # Intended for the case where fuzzy_number_n_dim correspond to the n dimensional antecedent of a rule
        for antecedent in fuzzy_number_n_dim:
            # If Gaussian, pass through unchanged
            if _is_gaussian(antecedent.set):
                FN_Ndim_adapted.append(antecedent.set)
                continue
            
            fset_type = str(type(antecedent.set))
            if fset_type.find('InferiorBorder') != -1:
                comp = [antecedent.set.top, antecedent.set.top, antecedent.set.top, antecedent.set.end]
            elif fset_type.find('SuperiorBorder') != -1:
                comp = [antecedent.set.ini, antecedent.set.top, antecedent.set.top, antecedent.set.top]
            elif fset_type.find('Triangular') != -1:
                comp = [antecedent.set.ini, antecedent.set.top, antecedent.set.top, antecedent.set.end]
            elif fset_type.find('Trapezoidal') != -1:
                comp = [antecedent.set.ini, antecedent.set.top1, antecedent.set.top2, antecedent.set.end]
            else:
                raise ValueError(f"Unsupported membership function type: {fset_type}")
            FN_Ndim_adapted.append(comp)

    elif ftype == 'rule_consequent':  # Intended for the case where fuzzy_number_n_dim correspond to the consequent of a rule
        cons = fuzzy_number_n_dim
        fset_type = str(type(cons.set))
        if fset_type.find('InferiorBorder') != -1:
            comp = [cons.set.top, cons.set.top, cons.set.top, cons.set.end]
        if fset_type.find('SuperiorBorder') != -1:
            comp = [cons.set.ini, cons.set.top, cons.set.top, cons.set.top]
        if fset_type.find('Triangular') != -1:
            comp = [cons.set.ini, cons.set.top, cons.set.top, cons.set.end]
        if fset_type.find('Trapezoidal') != -1:
            comp = [cons.set.ini, cons.set.top1, cons.set.top2, cons.set.end]
        FN_Ndim_adapted = comp
    
    return FN_Ndim_adapted


def fuzzy_imp(a, b, imp_type='luka', param=1):
    ''' Implements fuzzy implications I(a,b). a and b can be arrays of the same size'''
    
    a = np.asarray(a)
    b = np.asarray(b)

    if imp_type == 'luka':
        imp_a_b = np.minimum(1, 1 - a + b)
    elif imp_type == 'godel':
        imp_a_b = np.where(a <= b, 1, b)
    elif imp_type == 'goguen':
        imp_a_b = np.where(a <= b, 1, b / a)
    elif imp_type == 'hamacher':
        imp_a_b = np.where(a <= b, 1, b * (param + a - param * a) / (b * (param + a - param * a) + a - b))
    elif imp_type == 'dombi':
        # Handle edge cases to avoid division by zero
        # When a=0: implication should be 1 (anything implies from false)
        # When b=0 and a>0: implication should be 0
        # When a=1 and b<1: standard formula
        eps = 1e-10
        a_safe = np.clip(a, eps, 1 - eps)
        b_safe = np.clip(b, eps, 1 - eps)
        
        ratio_b = (1 - b_safe) / b_safe
        ratio_a = (1 - a_safe) / a_safe
        
        # Avoid negative base for fractional exponent
        diff = np.maximum(ratio_b ** param - ratio_a ** param, 0)
        imp_a_b = np.where(a <= b, 1, 1 / (1 + diff ** (1 / param)))

    return imp_a_b


def tnorms(a_constant, b_array, tnorm_type='product'):
    '''Implements a t-norm. a_constant is a single number. b_array is an array'''

    if isinstance(tnorm_type, str):
        if tnorm_type == 'product':
            out = a_constant * b_array
        elif tnorm_type == 'min':
            out = np.minimum(a_constant, b_array)
        elif tnorm_type == 'luka':
            aux = a_constant + b_array - 1
            out = np.maximum(0, aux)
        else:
            # Unknown string t-norm, fall back to product
            out = a_constant * b_array
    else:
        param = tnorm_type[1]
        if tnorm_type[0] == 'hamacher':
            num = a_constant * b_array
            den = param + (1 - param) * (a_constant + b_array - a_constant * b_array)
            # Avoid division by zero
            den = np.where(den == 0, 1e-10, den)
            out = num / den
        else:
            # Unknown parametric t-norm, fall back to product
            out = a_constant * b_array
    
    return out


def aggregation(x, agg_method='avg', param=[1]):
    ''' aggregation function'''

    if isinstance(agg_method, str):
        if agg_method == 'avg':
            agg_output = np.mean(x)
        elif agg_method == 'product':
            agg_output = np.prod(x)
        elif agg_method == 'min':
            agg_output = np.min(x)
        elif agg_method == 'max':
            agg_output = np.max(x)
        else:
            # Unknown string method, fall back to average
            agg_output = np.mean(x)
    else: 
        if agg_method[0] == 'weighted_avg':
            param = agg_method[1]
            # If weights are empty or sum to zero, fall back to simple average
            if len(param) == 0 or np.sum(param) == 0:
                agg_output = np.mean(x)
            else:
                agg_output = np.sum(np.array(x) * np.array(param)) / np.sum(param)
        else:
            # Unknown list method, fall back to average
            agg_output = np.mean(x)
    
    return agg_output


def membership(FN, U, disc=100):
    ''' calculates membership function of a fuzzy number [a,b,c,d]'''
    X = np.linspace(U[0], U[1], disc)
    FN_U = []
    for x in X:
        if (FN[1] <= x) and (x <= FN[2]):
            FN_U.append(1)
        elif (FN[0] < FN[1]) and (FN[0] <= x) and (x <= FN[1]):
            FN_U.append((x - FN[0]) / (FN[1] - FN[0]))
        elif (FN[2] < FN[3]) and (FN[2] <= x) and (x <= FN[3]):
            FN_U.append((x - FN[3]) / (FN[2] - FN[3]))
        else:
            FN_U.append(0)
    
    FN_U = np.array(FN_U)
    return FN_U


def antecedents_names(input_string):
    result = []
    length = len(input_string)

    for i in range(2, length):
        if input_string[i:i+2] == ' =':
            result.append(input_string[i-2:i])

    return result


def get_non_repeated_strings(list_of_lists, j):
    unique_strings = set()

    for lst in list_of_lists:
        unique_strings.add(lst[j])

    return list(unique_strings)


def cuenta_antecedentes(rule_base):
    Ant_names_list = []
    for rule in rule_base.ruleBase:
        input_string = str(rule.antecedents)
        Ant_names_list.append(antecedents_names(input_string))

    Antecedentes_list = []
    for j in range(len(Ant_names_list[0])):
        antecedente_j = get_non_repeated_strings(Ant_names_list, j)
        Antecedentes_list.append(sorted(antecedente_j))

    ANT_positions = []
    for ant in Ant_names_list:
        # Initialize an empty list to store the positions
        positions_list = []
        # Iterate over each element in ant and find its position in the corresponding list
        for element, sublist in zip(ant, Antecedentes_list):
            position = sublist.index(element)
            positions_list.append(position)
        ANT_positions.append(positions_list)

    return Antecedentes_list, Ant_names_list, ANT_positions


def interseccion_intervalos(INT_1, INT_2):
    ''' Determines if there's intersection between intervals. INTs are list of lists. The intersection is carried out
    between corresponding elements of both lists. The output is a boolean '''
    
    # Check for intersection for each pair of intervals
    intersect_array = [not (interval1[0] > interval2[1] or interval2[0] > interval1[1]) for interval1, interval2 in zip(INT_1, INT_2)]

    return intersect_array


# ============================================================================
# Core Functions
# ============================================================================

def sort_antecedents_spatially(antecedents_list, dimension_index):
    """
    Sort antecedents spatially by core positions for a given dimension.
    Returns: (spatially_sorted_antecedents, cores, alphabetical_to_spatial_map, spatial_to_alphabetical_map)
    """
    # Get unique antecedents
    aux = []
    seen = set()
    for ant_list in antecedents_list:
        ant = ant_list[dimension_index]
        ant_id = id(ant)
        if ant_id not in seen:
            aux.append(ant)
            seen.add(ant_id)
    
    # Sort alphabetically
    aux_str = [str(ant) for ant in aux]
    aux_str_order = sorted(range(len(aux_str)), key=lambda k: aux_str[k])
    aux_alphabetical = [aux[i] for i in aux_str_order]
    
    # Get cores
    aux_alphabetical_formatted = format_FN_N_Dim(aux_alphabetical, 'rule_antecedent')
    cores_alphabetical = [ant[1:3] for ant in aux_alphabetical_formatted]
    
    # Sort spatially by core positions (Equation 24: a_1^1 ≤ ā_1^1 < a_2^1 ≤ ā_2^1 < ...)
    core_centers = [(c[0] + c[1]) / 2.0 for c in cores_alphabetical]
    spatial_order = sorted(range(len(core_centers)), key=lambda k: (core_centers[k], cores_alphabetical[k][0]))
    aux_spatial = [aux_alphabetical[i] for i in spatial_order]
    cores_spatial = [cores_alphabetical[i] for i in spatial_order]
    
    # Validate Equation (24) ordering: ā_j^1 < a_{j+1}^1
    for k in range(len(cores_spatial) - 1):
        if cores_spatial[k][1] >= cores_spatial[k + 1][0]:
            raise ValueError(
                f"Equation (24) violation in dimension {dimension_index}: "
                f"Core {k} right ({cores_spatial[k][1]}) >= Core {k+1} left ({cores_spatial[k + 1][0]})"
            )
    
    # Create mappings
    alphabetical_to_spatial = {alpha_pos: spatial_order.index(alpha_pos) for alpha_pos in range(len(aux_alphabetical))}
    spatial_to_alphabetical = {spatial_pos: spatial_order[spatial_pos] for spatial_pos in range(len(spatial_order))}
    
    return aux_spatial, cores_spatial, alphabetical_to_spatial, spatial_to_alphabetical


def D_LR(input_cores_matrix_format, antec_cores_by_dim_spatial):
    """
    Calculate D_LR with denominators based on spatial ordering.
    
    Equations (25)-(27): dl, dr, delta_DL, delta_DR
    Equations (28)-(29): Den_L, Den_R
    
    Den_L: a_j^1 - ā_{j-1}^1
    Den_R: a_{j+1}^1 - ā_j^1
    """
    D_L, D_R, delta_DL, delta_DR, Den_L, Den_R = [], [], [], [], [], []

    for j in range(len(input_cores_matrix_format)):
        Cj = antec_cores_by_dim_spatial[j]  # Spatially ordered cores
        C = input_cores_matrix_format[j]
        C = [C] * len(Cj)

        int_intervalos = ~np.array(interseccion_intervalos(C, Cj))

        Cj_ul = np.array([c[0] for c in Cj])  # Left cores
        Cj_ol = np.array([c[1] for c in Cj])  # Right cores
        C_ul = np.array([c[0] for c in C])    # Input left core
        C_ol = np.array([c[1] for c in C])     # Input right core
        
        # Equation (25): d_j^L(X) = a_j^1 - x̄^1
        dl = (Cj_ul - C_ol) * int_intervalos
        
        # Equation (26): d_j^R(X) = x^1 - ā_j^1
        dr = (C_ul - Cj_ol) * int_intervalos
        
        # Equation (27): δ(x)
        delta_DL.append(np.array([1 if num >= 0 else 0 for num in dl]))
        delta_DR.append(np.array([1 if num >= 0 else 0 for num in dr]))
        D_L.append(dl)
        D_R.append(dr)

        # Equation (28): Den_L = a_j^1 - ā_{j-1}^1
        den_L = np.zeros(len(Cj_ul))
        if len(Cj_ul) > 1:
            den_L[1:] = Cj_ul[1:] - Cj_ol[:-1]
            if np.any(den_L[1:] <= 0):
                raise ValueError(f"Den_L contains non-positive values in dimension {j}. "
                               f"Values: {den_L[1:]}, Cores: {Cj}")
        
        # Equation (29): Den_R = a_{j+1}^1 - ā_j^1
        den_R = np.zeros(len(Cj_ul))
        if len(Cj_ul) > 1:
            den_R[:-1] = Cj_ul[1:] - Cj_ol[:-1]
            if np.any(den_R[:-1] <= 0):
                raise ValueError(f"Den_R contains non-positive values in dimension {j}. "
                               f"Values: {den_R[:-1]}, Cores: {Cj}")
        
        Den_L.append(den_L)
        Den_R.append(den_R)

    return D_L, D_R, delta_DL, delta_DR, Den_L, Den_R


def A_FIS(input, rule_base, agg_method, disc, t_norm_type, imp_params=['luka', 1], A_FIS_type='conjunctive', **kwargs):
    """
    A-FIS: Fuzzy Inference System based on A-subsethood measure.
    
    For each rule:
    1. Calculate S_A (A-subsethood activation)
    2. Scale consequent membership by S_A using t-norm
    3. Take supremum of all scaled consequents
    """
    num_dims = len(rule_base.inputRanges)
    num_rules = len(rule_base.ruleBase)
    
    # Get antecedents list
    Antecedentes_list = [rule.antecedents for rule in rule_base.ruleBase]
    
    # Build consistent antecedent indexing per dimension
    antec_by_dim_alphabetical = []
    cores_by_dim_spatial = []
    spatial_positions_per_rule = []
    alphabetical_positions_per_rule = []

    for j in range(num_dims):
        # Get unique antecedents for this dimension
        aux = [ant[j] for ant in Antecedentes_list]
        aux = list(set(aux))
        aux_str = [str(ant) for ant in aux]
        aux_str_order = sorted(range(len(aux_str)), key=lambda k: aux_str[k])
        aux_alphabetical = [aux[i] for i in aux_str_order]
        
        # Format antecedents as [ini, top1, top2, end]
        aux_alphabetical_formatted = format_FN_N_Dim(aux_alphabetical, 'rule_antecedent')
        antec_by_dim_alphabetical.append(aux_alphabetical_formatted)
        
        # Get spatial ordering for D_LR calculation
        aux_spatial, cores_spatial, alpha_to_spatial, _ = sort_antecedents_spatially(Antecedentes_list, j)
        cores_by_dim_spatial.append(cores_spatial)
        
        # Map each rule to its positions
        spatial_pos_dim = []
        alpha_pos_dim = []
        for rule_idx, rule_ants in enumerate(Antecedentes_list):
            ant = rule_ants[j]
            try:
                alpha_pos = aux_alphabetical.index(ant)
            except ValueError:
                alpha_pos = next((i for i, a in enumerate(aux_alphabetical) if id(a) == id(ant)), None)
            spatial_pos = alpha_to_spatial[alpha_pos]
            spatial_pos_dim.append(spatial_pos)
            alpha_pos_dim.append(alpha_pos)
        spatial_positions_per_rule.append(spatial_pos_dim)
        alphabetical_positions_per_rule.append(alpha_pos_dim)

    # Calculate SVI for each antecedent in each dimension
    imp_type = imp_params[0]
    imp_param = imp_params[1] if len(imp_params) > 1 else 1
    
    # Check if any input dimension is Gaussian (enables numerical path)
    has_gaussian = _has_gaussian_input(input)
    
    SVI_list = []
    for dim_idx in range(num_dims):
        domain = rule_base.inputRanges[dim_idx]
        inp = input[dim_idx]
        svi_dim = []
        for ant in antec_by_dim_alphabetical[dim_idx]:
            # Use auto-dispatcher: numerical for Gaussian, analytical otherwise
            nu_X_vee_A = A_vee_B.nu_A_vee_B_auto(inp, ant, domain)
            nu_A = A_vee_B.nu_A_vee_B_auto(ant, ant, domain)
            svi = fuzzy_imp(nu_X_vee_A, nu_A, imp_type, imp_param)
            svi_dim.append(svi)
        SVI_list.append(svi_dim)
    
    # Check if input is EQUAL to any rule's antecedent in ALL dimensions
    # If so, that rule's activation = 1, all others = 0
    # For trapezoidal: input = antecedent if all four values match exactly
    # NOTE: Skip equality check if any dimension has Gaussian input (not comparable)
    rules_with_input_equal = []
    
    if has_gaussian:
        # Gaussian inputs: skip equality check, proceed to normal calculation
        rules_with_input_equal = [False] * num_rules
    else:
        # Standard trapezoidal inputs: perform equality check
        for rule_idx in range(num_rules):
            is_equal_all_dims = True
            for dim_idx in range(num_dims):
                alpha_pos = alphabetical_positions_per_rule[dim_idx][rule_idx]
                input_dim = input[dim_idx]
                antec_dim = antec_by_dim_alphabetical[dim_idx][alpha_pos]
                
                # Check equality condition: input must exactly match antecedent
                is_equal_dim = (input_dim[0] == antec_dim[0] and  # ini
                               input_dim[3] == antec_dim[3] and    # end
                               input_dim[1] == antec_dim[1] and    # top1
                               input_dim[2] == antec_dim[2])       # top2
                
                if not is_equal_dim:
                    is_equal_all_dims = False
                    break
            
            rules_with_input_equal.append(is_equal_all_dims)
    
    # If input equals any rule's antecedent, use direct activation
    if any(rules_with_input_equal):
        S_A_agg = [1.0 if is_equal else 0.0 for is_equal in rules_with_input_equal]
    else:
        # Normal calculation path
        # Calculate D_LR values - use helper for Gaussian-aware core extraction
        input_cores = [_get_input_core(input[j]) for j in range(num_dims)]
        DL, DR, delta_DL, delta_DR, Den_L, Den_R = D_LR(input_cores, cores_by_dim_spatial)

        # Calculate S_A for each rule
        S_A_agg = []
        for rule_idx in range(num_rules):
            S_A_per_dim = []
            
            for dim_idx in range(num_dims):
                alpha_pos = alphabetical_positions_per_rule[dim_idx][rule_idx]
                spatial_pos = spatial_positions_per_rule[dim_idx][rule_idx]
                
                svi = SVI_list[dim_idx][alpha_pos]
                dl = DL[dim_idx][spatial_pos]
                dr = DR[dim_idx][spatial_pos]
                delta_dl = delta_DL[dim_idx][spatial_pos]
                delta_dr = delta_DR[dim_idx][spatial_pos]
                
                num_antecedents = len(cores_by_dim_spatial[dim_idx])
                is_first = (spatial_pos == 0)
                is_last = (spatial_pos == num_antecedents - 1)
                
                # S^L,A (Equation 28)
                if is_first:
                    sl = svi * delta_dl
                else:
                    sl = svi * max((1 - dl / Den_L[dim_idx][spatial_pos]), 0) * delta_dl
                
                # S^R,A (Equation 29)
                if is_last:
                    sr = svi * delta_dr
                else:
                    sr = svi * max((1 - dr / Den_R[dim_idx][spatial_pos]), 0) * delta_dr
                
                # S_A for this dimension (Equation 30)
                sA_dim = max(sl, sr)
                S_A_per_dim.append(sA_dim)

            # Aggregate across dimensions
            sA_rule = aggregation(S_A_per_dim, agg_method)
            S_A_agg.append(sA_rule)
    
    S_A_agg = np.array(S_A_agg)
    
    # =========================================================================
    # OUTPUT CALCULATION - Simple and correct:
    # 1. For each rule: scale consequent by S_A using t-norm
    # 2. Take supremum (pointwise max) of all scaled consequents
    # =========================================================================
    U = np.linspace(rule_base.outputRange[0], rule_base.outputRange[1], disc)
    
    # Scale each rule's consequent by its S_A
    scaled_outputs = []
    for rule_idx in range(num_rules):
        cons = rule_base.ruleBase[rule_idx].consequent
        cons_formatted = format_FN_N_Dim(cons, ftype='rule_consequent')
        cons_membership = membership(cons_formatted, rule_base.outputRange, disc)
        scaled_cons = tnorms(S_A_agg[rule_idx], cons_membership, t_norm_type)
        scaled_outputs.append(scaled_cons)
    
    # Supremum aggregation (pointwise maximum)
    output = np.maximum.reduce(scaled_outputs)
    
    # Build max_values dict for return (for compatibility)
    Cons_names = [antecedents_names(str(rule.consequent))[0] for rule in rule_base.ruleBase]
    max_values = {}
    for rule_idx, (sa, cons_name) in enumerate(zip(S_A_agg, Cons_names)):
        current_max, _ = max_values.get(cons_name, (float('-inf'), None))
        if sa > current_max:
            max_values[cons_name] = (sa, rule_idx)
    max_values = dict(sorted(max_values.items(), key=lambda item: item[1], reverse=True))
    
    return output, U, max_values

